# Uncomment this line, define a global platform for your project
platform :ios, '9.0'

target 'Cranbrook Kingswood' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cranbrook Kingswood
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 3.4'  
  pod 'Rollout.io', '~> 1.3.1'
  pod 'Unbox'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftMessages'
  pod 'PullToRefreshSwift'
end
